name: localize_it_annotation
description: Annotation for localize_it code generation. This package does nothing without localize_it too.
homepage: https://github.com/DieGlueckswurst/localize_it
repository: https://github.com/DieGlueckswurst/localize_it
issue_tracker: https://github.com/DieGlueckswurst/localize_it/issues
version: 1.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
dev_dependencies:
  test: 1.3.4
