name: localize_it_annotation
description: Annotation for localize_it code generation. This package does nothing without localize_it too.
homepage: https://github.com/DieGlueckswurst/localize_it
repository: https://github.com/DieGlueckswurst/localize_it
issue_tracker: https://github.com/DieGlueckswurst/localize_it/issues
version: 4.0.0
environment:
  sdk: ^3.9.0
dependencies:
dev_dependencies:
  test: ^1.31.0
