name: localize_it
description: A tool for making localizing your Flutter App easy peasy lemmon squeezy.
homepage: https://github.com/DieGlueckswurst/localize_it
repository: https://github.com/DieGlueckswurst/localize_it
issue_tracker: https://github.com/DieGlueckswurst/localize_it/issues
version: 1.1.6
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  localize_it_annotation: ^2.0.0
  analyzer: any
  build: ^2.3.1
  source_gen: ^2.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^2.0.0

