name: localize_it
description: A tool for making localizing your Flutter App easy peasy lemmon squeezy.
homepage: https://github.com/DieGlueckswurst/localize_it
repository: https://github.com/DieGlueckswurst/localize_it
issue_tracker: https://github.com/DieGlueckswurst/localize_it/issues
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  localize_it_annotation: ^1.0.0
  analyzer: ^5.1.0
  build: ^2.3.1
  source_gen: ^1.2.6
  http: ^0.13.5

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
  flutter_lints: ^2.0.0

